const TEAM_CODES = [
    { name: 'Arsenal', code: 'ars' },
    { name: 'Aston Villa', code: 'ast' },
    { name: 'Brighton', code: 'bha' },
    { name: 'Burnley', code: 'bur' },
    { name: 'Chelsea', code: 'che' },
    { name: 'Crystal Palace', code: 'pal' },
    { name: 'Everton', code: 'eve' },
    { name: 'Liverpool', code: 'liv' },
    { name: 'Fulham', code: 'ful' },
    { name: 'Leeds', code: 'lee' },
    { name: 'Man United', code: 'mnu' },
    { name: 'Man City', code: 'mnc' },
    { name: 'Leicester', code: 'lei' },
    { name: 'Newcastle', code: 'new' },
    { name: 'Southampton', code: 'sot' },
    { name: 'Spurs', code: 'tot' },
    { name: 'Sheffield United', code: 'shu' },
    { name: 'Wolves', code: 'wol' },
    { name: 'West Ham', code: 'whu' },
    { name: 'West Brom', code: 'wba' },
]
