[{ "home": "Brighton", "away": "Man United", "result": "pending" },
    { "home": "Crystal Palace", "away": "Everton", "result": "pending" },
    { "home": "West Brom", "away": "Chelsea", "result": "pending" },
    { "home": "Burnley", "away": "Southampton", "result": "pending" },
    { "home": "Sheffield United", "away": "Leeds", "result": "pending" },
    { "home": "Spurs", "away": "Newcastle", "result": "pending" },
    { "home": "Man City", "away": "Leicester", "result": "pending" },
    { "home": "West Ham", "away": "Wolves", "result": "pending" },
    { "home": "Fulham", "away": "Aston Villa", "result": "pending" },
    { "home": "Liverpool", "away": "Arsenal", "result": "pending" }]