require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'
require_relative '../node_modules/react-native-unimodules/cocoapods.rb'

platform :ios, '10.0'

target 'LastPunditStanding' do
  use_unimodules!
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'
  pod 'react-native-splash-screen', :path => '../node_modules/react-native-splash-screen'
  pod 'Firebase/Auth'
  pod 'Firebase/Messaging'	
  pod 'Firebase/Database'

  target 'LastPunditStandingTests' do
    inherit! :complete
    # Pods for testing
  end
end

post_install do |installer|
  installer.pods_project.build_configurations.each do |config|
    config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
  end
end

target 'LastPunditStanding-tvOS' do
  # Pods for LastPunditStanding-tvOS

  target 'LastPunditStanding-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
