export const PREMIER_LEAGUE_TEAMS = [
    { value: 'Arsenal', label: 'Arsenal', id: 1 },
    { value: 'Aston Villa', label: 'Aston Villa', id: 2 },
    { value: 'Brighton', label: 'Brighton', id: 3 },
    { value: 'Burnley', label: 'Burnley', id: 4 },
    { value: 'Chelsea', label: 'Chelsea', id: 5 },
    { value: 'Crystal Palace', label: 'Crystal Palace', id: 6 },
    { value: 'Everton', label: 'Everton', id: 7 },
    { value: 'Fulham', label: 'Fulham', id: 8 },
    { value: 'Leeds', label: 'Leeds', id: 9 },
    { value: 'Leicester', label: 'Leicester', id: 10 },
    { value: 'Liverpool', label: 'Liverpool', id: 11 },
    { value: 'Man City', label: 'Man City', id: 12 },
    { value: 'Man United', label: 'Man United', id: 13 },
    { value: 'Newcastle', label: 'Newcastle', id: 14 },
    { value: 'Sheffield United', label: 'Sheffield United', id: 15 },
    { value: 'Southampton', label: 'Southampton', id: 16 },
    { value: 'Spurs', label: 'Spurs', id: 17 },
    { value: 'West Brom', label: 'West Brom', id: 18 },
    { value: 'West Ham', label: 'West Ham', id: 19 },
    { value: 'Wolves', label: 'Wolves', id: 20 },
]
