export const PREMIER_LEAGUE_TEAMS = [
    { value: 'Arsenal', code: '' },
    { value: 'Aston Villa', code: '' },
    { value: 'Brighton', code: '' },
    { value: 'Burnley', code: '' },
    { value: 'Chelsea', code: '' },
    { value: 'Crystal Palace', code: '' },
    { value: 'Everton', code: '' },
    { value: 'Fulham', code: '' },
    { value: 'Leeds', code: '' },
    { value: 'Leicester', code: '' },
    { value: 'Liverpool', code: '' },
    { value: 'Man City', code: '' },
    { value: 'Man United', code: '' },
    { value: 'Newcastle', code: '' },
    { value: 'Sheffield United', code: '' },
    { value: 'Southampton', code: '' },
    { value: 'Spurs', code: '' },
    { value: 'West Brom', code: '' },
    { value: 'West Ham', code: '' },
    { value: 'Wolves', code: '' },
]
