export const PREMIER_LEAGUE_TEAMS = [
    { value: 'Arsenal', code: 'ARS' },
    { value: 'Aston Villa', code: 'AST' },
    { value: 'Brighton', code: 'BHA' },
    { value: 'Burnley', code: 'BUR' },
    { value: 'Chelsea', code: 'CHE' },
    { value: 'Crystal Palace', code: 'PAL' },
    { value: 'Everton', code: 'EVE' },
    { value: 'Fulham', code: 'FUL' },
    { value: 'Leeds', code: 'LEE' },
    { value: 'Leicester', code: 'LEI' },
    { value: 'Liverpool', code: 'LIV' },
    { value: 'Man City', code: 'MNC' },
    { value: 'Man United', code: 'MNU' },
    { value: 'Newcastle', code: 'NEW' },
    { value: 'Sheffield United', code: 'SHU' },
    { value: 'Southampton', code: 'SOT' },
    { value: 'Spurs', code: 'TOT' },
    { value: 'West Brom', code: 'WBA' },
    { value: 'West Ham', code: 'WHU' },
    { value: 'Wolves', code: 'WOL' },
]
